#!/usr/bin/env php
<?php

include_once 'vendor/autoload.php';

define('IN_IA', true);

/**
 * 创建console对象
 * @var $app \og\http\App
 */


$app = og\http\Container::getInstance()->make(og\http\App::class,
    [
        __DIR__.'/',
        dirname(dirname(__DIR__)).'/',
        '',
    ]
);


//执行命令
\og\console\Console::run($app);